"""Check every PDF under gate-da/data and write manifest.csv and MANIFEST.md.

Run with a Python that has pypdf and cryptography:
    python gate-da/scripts/build_manifest.py
"""
import csv
import glob
import hashlib
import os
import re
from collections import defaultdict

import pypdf

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "data")
ROOT = os.path.normpath(ROOT)
NAME = re.compile(r"^(?P<paper>[A-Z]+)_(?P<year>\d{4}|SAMPLE)(?:_S(?P<set>\d))?_(?P<kind>QP|KEY)$")


def read_sources():
    """Merge every sources*.csv into {relative file path: row}."""
    sources = {}
    for path in glob.glob(os.path.join(ROOT, "**", "sources*.csv"), recursive=True):
        base = os.path.relpath(os.path.dirname(path), ROOT)
        with open(path, newline="", encoding="utf-8") as f:
            for row in csv.DictReader(f):
                rel = row.get("file", "").strip()
                if not rel:
                    continue
                # Agents wrote paths relative to either data/ or their paper folder.
                for candidate in (rel, os.path.join(base, rel)):
                    if os.path.exists(os.path.join(ROOT, candidate)):
                        sources[os.path.normpath(candidate)] = row
                        break
                else:
                    sources[os.path.normpath(os.path.join(base, os.path.basename(rel)))] = row
    return sources


def text_for(pdf_path, reader):
    txt_path = pdf_path[:-4] + ".txt"
    if os.path.exists(txt_path):
        with open(txt_path, encoding="utf-8", errors="ignore") as f:
            return f.read()
    return "\n".join((p.extract_text() or "") for p in reader.pages)


def question_numbers(text):
    return sorted({int(n) for n in re.findall(r"Q\.\s*(\d{1,2})\b", text) if 0 < int(n) <= 90})


def main():
    sources = read_sources()
    rows = []
    for pdf in sorted(glob.glob(os.path.join(ROOT, "**", "*.pdf"), recursive=True)):
        rel = os.path.relpath(pdf, ROOT)
        stem = os.path.splitext(os.path.basename(pdf))[0]
        m = NAME.match(stem)
        with open(pdf, "rb") as f:
            data = f.read()
        row = {
            "file": rel,
            "paper": m["paper"] if m else "",
            "year": m["year"] if m else "",
            "set": (m["set"] or "") if m else "",
            "kind": m["kind"] if m else "",
            "bytes": len(data),
            "sha256": hashlib.sha256(data).hexdigest(),
            "is_pdf": data[:5] == b"%PDF-",
            "pages": "",
            "text_chars": "",
            "questions": "",
            "problem": "" if m else "unexpected file name",
        }
        try:
            reader = pypdf.PdfReader(pdf)
            if reader.is_encrypted:
                # The 2021 CS papers are encrypted with an empty user password.
                # Decrypting them needs the cryptography package.
                reader.decrypt("")
            text = text_for(pdf, reader)
            row["pages"] = len(reader.pages)
            row["text_chars"] = len(text.strip())
            # Key layouts vary too much across years to count rows reliably,
            # so question numbers are only reported for papers.
            nums = question_numbers(text) if row["kind"] == "QP" else []
            if nums:
                row["questions"] = f"{len(nums)} ({nums[0]}-{nums[-1]})"
            # In this dataset, papers with a real text layer have 500+ characters a
            # page and keys 390+. Below these limits the questions or answers are images.
            per_page = row["text_chars"] / max(row["pages"], 1)
            if per_page < (400 if row["kind"] == "QP" else 200):
                row["problem"] = "mostly scanned images, little extractable text"
        except Exception as e:  # keep going; the manifest records the failure
            row["problem"] = f"unreadable: {e.__class__.__name__}"
        src = sources.get(os.path.normpath(rel), {})
        row["source_url"] = src.get("source_url", "")
        row["key_status"] = src.get("key_status", "")
        row["notes"] = src.get("notes", "")
        if not row["is_pdf"]:
            row["problem"] = "not a PDF"
        rows.append(row)

    fields = list(rows[0].keys()) if rows else []
    with open(os.path.join(ROOT, "manifest.csv"), "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)

    by_paper = defaultdict(list)
    for r in rows:
        by_paper[r["paper"] or "other"].append(r)
    total_mb = sum(r["bytes"] for r in rows) / 1e6
    lines = [
        "# Dataset manifest",
        "",
        f"{len(rows)} PDFs, {total_mb:.1f} MB. Generated by `scripts/build_manifest.py`; "
        "`manifest.csv` has the same data plus SHA-256 hashes.",
        "",
    ]
    for paper in sorted(by_paper):
        lines += [f"## {paper}", "", "| File | Pages | Text chars | Question numbers found | Key status | Source | Problem |",
                  "|---|---|---|---|---|---|---|"]
        for r in by_paper[paper]:
            src = f"[link]({r['source_url']})" if r["source_url"] else ""
            lines.append(f"| {r['file']} | {r['pages']} | {r['text_chars']} | {r['questions']} | "
                         f"{r['key_status']} | {src} | {r['problem']} |")
        lines.append("")
    with open(os.path.join(ROOT, "MANIFEST.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"{len(rows)} PDFs, {total_mb:.1f} MB")
    for r in rows:
        if r["problem"]:
            print("PROBLEM", r["file"], r["problem"])


if __name__ == "__main__":
    main()
